-- DO NOT RUN until the Supabase dashboard visibly shows project CMIPtst.
begin;
create extension if not exists pgcrypto;
create type public.app_role as enum ('admin','receptionist','doctor');
create type public.queue_status as enum ('waiting','called','in_service','finished','absent','cancelled');

create table public.profiles(id uuid primary key references auth.users(id) on delete cascade,full_name text not null,role public.app_role not null,active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.doctors(id bigint generated always as identity primary key,profile_id uuid unique not null references public.profiles(id),name text not null,crm text,active boolean not null default true,created_at timestamptz not null default now());
create table public.offices(id bigint generated always as identity primary key,name text not null unique,active boolean not null default true,created_at timestamptz not null default now());
create table public.doctor_sessions(id bigint generated always as identity primary key,doctor_id bigint not null references public.doctors(id),office_id bigint not null references public.offices(id),started_at timestamptz not null default now(),ended_at timestamptz,created_by uuid not null default auth.uid() references auth.users(id));
create unique index one_active_session_per_doctor on public.doctor_sessions(doctor_id) where ended_at is null;
create unique index one_active_doctor_per_office on public.doctor_sessions(office_id) where ended_at is null;

create table public.patients(id bigint generated always as identity primary key,full_name text not null,birth_date date not null,cpf text,phone text,zip_code text,street text,street_number text,complement text,district text,city text,state text,created_by uuid not null default auth.uid() references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),constraint valid_cpf_shape check(cpf is null or cpf~'^\d{11}$'),constraint valid_uf check(state is null or state~'^[A-Z]{2}$'));
create unique index patients_cpf_unique on public.patients(cpf) where cpf is not null;
create index patients_name_idx on public.patients using gin(to_tsvector('simple',full_name));

create table public.service_points(id bigint generated always as identity primary key,name text not null unique,active boolean not null default true);
create table public.ticket_counters(service_point_id bigint primary key references public.service_points(id) on delete cascade,next_number int not null default 1 check(next_number between 1 and 1000),updated_at timestamptz not null default now());
create table public.ticket_calls(id bigint generated always as identity primary key,service_point_id bigint not null references public.service_points(id),number int not null check(number between 1 and 1000),call_kind text not null check(call_kind in('next','specific','recall')),called_by uuid not null references auth.users(id),called_at timestamptz not null default now(),original_call_id bigint references public.ticket_calls(id));
create index ticket_calls_latest_idx on public.ticket_calls(service_point_id,called_at desc);

create table public.medical_queue(id bigint generated always as identity primary key,patient_id bigint not null references public.patients(id),doctor_id bigint not null references public.doctors(id),status public.queue_status not null default 'waiting',created_by uuid not null references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index medical_queue_doctor_status_idx on public.medical_queue(doctor_id,status,created_at);
create table public.queue_history(id bigint generated always as identity primary key,queue_id bigint not null references public.medical_queue(id),event text not null,from_status public.queue_status,to_status public.queue_status,previous_doctor_id bigint references public.doctors(id),new_doctor_id bigint references public.doctors(id),performed_by uuid not null references auth.users(id),reason text,created_at timestamptz not null default now());
create table public.display_panels(id bigint generated always as identity primary key,name text not null,slug text not null unique,active boolean not null default true,public_token uuid not null default gen_random_uuid());
create table public.display_panel_offices(panel_id bigint references public.display_panels(id) on delete cascade,office_id bigint references public.offices(id) on delete cascade,primary key(panel_id,office_id));
create table public.patient_calls(id bigint generated always as identity primary key,queue_id bigint not null references public.medical_queue(id),doctor_session_id bigint not null references public.doctor_sessions(id),call_kind text not null check(call_kind in('call','recall')),called_by uuid not null references auth.users(id),called_at timestamptz not null default now(),original_call_id bigint references public.patient_calls(id));
create table public.patient_call_displays(patient_call_id bigint references public.patient_calls(id) on delete cascade,panel_id bigint references public.display_panels(id) on delete cascade,primary key(patient_call_id,panel_id));

create or replace function public.my_role() returns public.app_role language sql stable security definer set search_path=public as $$select role from profiles where id=auth.uid() and active$$;
create or replace function public.my_doctor_id() returns bigint language sql stable security definer set search_path=public as $$select d.id from doctors d join profiles p on p.id=d.profile_id where p.id=auth.uid() and p.active and d.active$$;
revoke all on function public.my_role() from public; grant execute on function public.my_role() to authenticated;
revoke all on function public.my_doctor_id() from public; grant execute on function public.my_doctor_id() to authenticated;

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$begin insert into profiles(id,full_name,role) values(new.id,coalesce(new.raw_user_meta_data->>'full_name',new.email),'receptionist');return new;end$$;
create trigger auth_user_profile after insert on auth.users for each row execute function public.handle_new_user();

create or replace function public.assert_reception() returns void language plpgsql security definer set search_path=public as $$begin if my_role() not in ('admin','receptionist') then raise exception 'not authorized' using errcode='42501';end if;end$$;
create or replace function public.set_next_ticket(p_service_point_id bigint,p_number int) returns void language plpgsql security definer set search_path=public as $$begin perform assert_reception();if p_number not between 1 and 1000 then raise exception 'number outside range';end if;insert into ticket_counters values(p_service_point_id,p_number,now()) on conflict(service_point_id) do update set next_number=excluded.next_number,updated_at=now();end$$;
create or replace function public.call_next_ticket(p_service_point_id bigint) returns jsonb language plpgsql security definer set search_path=public as $$declare n int;c ticket_calls;begin perform assert_reception();insert into ticket_counters values(p_service_point_id,1,now()) on conflict do nothing;select next_number into n from ticket_counters where service_point_id=p_service_point_id for update;insert into ticket_calls(service_point_id,number,call_kind,called_by) values(p_service_point_id,n,'next',auth.uid()) returning * into c;update ticket_counters set next_number=case when n=1000 then 1 else n+1 end,updated_at=now() where service_point_id=p_service_point_id;return jsonb_build_object('id',c.id,'display_number',lpad(n::text,4,'0'));end$$;
create or replace function public.call_specific_ticket(p_service_point_id bigint,p_number int) returns jsonb language plpgsql security definer set search_path=public as $$declare c ticket_calls;begin perform assert_reception();if p_number not between 1 and 1000 then raise exception 'number outside range';end if;insert into ticket_calls(service_point_id,number,call_kind,called_by) values(p_service_point_id,p_number,'specific',auth.uid()) returning * into c;return jsonb_build_object('id',c.id,'display_number',lpad(p_number::text,4,'0'));end$$;
create or replace function public.recall_ticket(p_service_point_id bigint) returns jsonb language plpgsql security definer set search_path=public as $$declare c ticket_calls;n ticket_calls;begin perform assert_reception();select * into c from ticket_calls where service_point_id=p_service_point_id and call_kind<>'recall' order by called_at desc limit 1;if c.id is null then raise exception 'no prior call';end if;insert into ticket_calls(service_point_id,number,call_kind,called_by,original_call_id) values(p_service_point_id,c.number,'recall',auth.uid(),c.id) returning * into n;return jsonb_build_object('id',n.id,'display_number',lpad(n.number::text,4,'0'));end$$;

create or replace function public.search_patients(p_term text default '') returns setof patients language plpgsql security definer set search_path=public as $$begin perform assert_reception();return query select p.* from patients p where p_term='' or p.full_name ilike '%'||p_term||'%' or p.cpf=regexp_replace(p_term,'\D','','g') order by p.full_name limit 50;end$$;
create or replace function public.save_patient(p_patient jsonb) returns patients language plpgsql security definer set search_path=public as $$declare p patients;begin perform assert_reception();if nullif(trim(p_patient->>'full_name'),'') is null or nullif(p_patient->>'birth_date','') is null then raise exception 'name and birth date required';end if;if p_patient->>'cpf' is not null and not public.is_valid_cpf(p_patient->>'cpf') then raise exception 'invalid CPF';end if;insert into patients(full_name,birth_date,cpf,phone,zip_code,street,street_number,complement,district,city,state,created_by) values(trim(p_patient->>'full_name'),(p_patient->>'birth_date')::date,nullif(p_patient->>'cpf',''),nullif(p_patient->>'phone',''),nullif(p_patient->>'zip_code',''),nullif(p_patient->>'street',''),nullif(p_patient->>'street_number',''),nullif(p_patient->>'complement',''),nullif(p_patient->>'district',''),nullif(p_patient->>'city',''),nullif(upper(p_patient->>'state'),''),auth.uid()) returning * into p;return p;end$$;
create or replace function public.is_valid_cpf(c text) returns boolean language plpgsql immutable as $$declare a int[];s int;d1 int;d2 int;i int;begin if c is null then return true;end if;if c!~'^\d{11}$' or c~'^(\d)\1{10}$' then return false;end if;a:=array(select substring(c from x for 1)::int from generate_series(1,11)x);s:=0;for i in 1..9 loop s:=s+a[i]*(11-i);end loop;d1:=(s*10)%11;if d1=10 then d1:=0;end if;s:=0;for i in 1..10 loop s:=s+a[i]*(12-i);end loop;d2:=(s*10)%11;if d2=10 then d2:=0;end if;return d1=a[10] and d2=a[11];end$$;

create or replace view public.active_doctors_public with(security_invoker=true) as select d.id doctor_id,d.name doctor_name,o.id office_id,o.name office_name from doctors d join doctor_sessions s on s.doctor_id=d.id and s.ended_at is null join offices o on o.id=s.office_id where d.active and o.active;
create or replace function public.start_doctor_session(p_office_id bigint) returns doctor_sessions language plpgsql security definer set search_path=public as $$declare did bigint;s doctor_sessions;begin did:=my_doctor_id();if did is null then raise exception 'not a doctor';end if;update doctor_sessions set ended_at=now() where doctor_id=did and ended_at is null;if exists(select 1 from doctor_sessions where office_id=p_office_id and ended_at is null) then raise exception 'office occupied' using errcode='23505';end if;insert into doctor_sessions(doctor_id,office_id,created_by) values(did,p_office_id,auth.uid()) returning * into s;return s;end$$;
create or replace function public.end_doctor_session() returns void language plpgsql security definer set search_path=public as $$begin update doctor_sessions set ended_at=now() where doctor_id=my_doctor_id() and ended_at is null;end$$;
create or replace function public.enqueue_patient(p_patient_id bigint,p_doctor_id bigint) returns medical_queue language plpgsql security definer set search_path=public as $$declare q medical_queue;begin perform assert_reception();insert into medical_queue(patient_id,doctor_id,created_by) values(p_patient_id,p_doctor_id,auth.uid()) returning * into q;insert into queue_history(queue_id,event,to_status,new_doctor_id,performed_by) values(q.id,'enqueued','waiting',p_doctor_id,auth.uid());return q;end$$;
create or replace function public.transfer_patient(p_queue_id bigint,p_new_doctor_id bigint,p_reason text default null) returns medical_queue language plpgsql security definer set search_path=public as $$declare q medical_queue;oldid bigint;oldst queue_status;begin perform assert_reception();select doctor_id,status into oldid,oldst from medical_queue where id=p_queue_id for update;update medical_queue set doctor_id=p_new_doctor_id,status='waiting',updated_at=now() where id=p_queue_id returning * into q;insert into queue_history(queue_id,event,from_status,to_status,previous_doctor_id,new_doctor_id,performed_by,reason) values(q.id,'transferred',oldst,'waiting',oldid,p_new_doctor_id,auth.uid(),p_reason);return q;end$$;
create or replace view public.doctor_queue_view with(security_invoker=true) as select q.id,p.full_name patient_name,q.status,q.created_at,o.name office_name from medical_queue q join patients p on p.id=q.patient_id left join doctor_sessions s on s.doctor_id=q.doctor_id and s.ended_at is null left join offices o on o.id=s.office_id where q.doctor_id=my_doctor_id() and q.status not in('finished','cancelled');
create or replace view public.reception_queue_view with(security_invoker=true) as select q.id,p.full_name patient_name,d.name doctor_name,q.status,q.created_at from medical_queue q join patients p on p.id=q.patient_id join doctors d on d.id=q.doctor_id;

create or replace function public.doctor_queue_action(p_queue_id bigint,p_action text) returns medical_queue language plpgsql security definer set search_path=public as $$declare q medical_queue;oldst queue_status;newst queue_status;s doctor_sessions;pc patient_calls;begin select * into q from medical_queue where id=p_queue_id and doctor_id=my_doctor_id() for update;if q.id is null then raise exception 'not authorized' using errcode='42501';end if;oldst:=q.status;newst:=case p_action when 'call' then 'called' when 'recall' then q.status when 'start' then 'in_service' when 'finish' then 'finished' when 'absent' then 'absent' when 'return' then 'waiting' else null end;if newst is null then raise exception 'invalid action';end if;if p_action in('call','recall') then select * into s from doctor_sessions where doctor_id=q.doctor_id and ended_at is null;if s.id is null then raise exception 'start a session first';end if;insert into patient_calls(queue_id,doctor_session_id,call_kind,called_by) values(q.id,s.id,p_action,auth.uid()) returning * into pc;insert into patient_call_displays select pc.id,dpo.panel_id from display_panel_offices dpo where dpo.office_id=s.office_id;end if;update medical_queue set status=newst,updated_at=now() where id=q.id returning * into q;insert into queue_history(queue_id,event,from_status,to_status,previous_doctor_id,new_doctor_id,performed_by) values(q.id,p_action,oldst,newst,q.doctor_id,q.doctor_id,auth.uid());return q;end$$;

create or replace function public.get_display_state(p_panel_slug text) returns jsonb language sql stable security definer set search_path=public as $$with panel as(select id from display_panels where slug=p_panel_slug and active),events as(select 'medical' kind,pc.called_at at,'m'||pc.id event_key,null::text display_number,p.full_name patient_name,o.name destination from patient_calls pc join patient_call_displays x on x.patient_call_id=pc.id join panel dp on dp.id=x.panel_id join medical_queue q on q.id=pc.queue_id join patients p on p.id=q.patient_id join doctor_sessions s on s.id=pc.doctor_session_id join offices o on o.id=s.office_id union all select 'ticket',tc.called_at,'t'||tc.id,lpad(tc.number::text,4,'0'),null,sp.name from ticket_calls tc join service_points sp on sp.id=tc.service_point_id where p_panel_slug='recepcao'),ordered as(select * from events order by at desc limit 8) select jsonb_build_object('current',(select to_jsonb(o) from ordered o order by at desc limit 1),'history',coalesce((select jsonb_agg(to_jsonb(h) order by at desc) from ordered h),'[]'::jsonb))$$;

alter table profiles enable row level security;alter table doctors enable row level security;alter table offices enable row level security;alter table doctor_sessions enable row level security;alter table patients enable row level security;alter table service_points enable row level security;alter table ticket_counters enable row level security;alter table ticket_calls enable row level security;alter table medical_queue enable row level security;alter table queue_history enable row level security;alter table display_panels enable row level security;alter table display_panel_offices enable row level security;alter table patient_calls enable row level security;alter table patient_call_displays enable row level security;
create policy own_profile on profiles for select to authenticated using(id=auth.uid() or my_role()='admin');
create policy staff_doctors on doctors for select to authenticated using(my_role() in('admin','receptionist','doctor'));
create policy staff_offices on offices for select to authenticated using(my_role() in('admin','receptionist','doctor'));
create policy sessions_read on doctor_sessions for select to authenticated using(my_role() in('admin','receptionist') or doctor_id=my_doctor_id());
create policy reception_patients on patients for select to authenticated using(my_role() in('admin','receptionist'));
create policy reception_points on service_points for select to authenticated using(my_role() in('admin','receptionist'));
create policy reception_queue on medical_queue for select to authenticated using(my_role() in('admin','receptionist') or doctor_id=my_doctor_id());
create policy doctor_patient_min on patients for select to authenticated using(exists(select 1 from medical_queue q where q.patient_id=patients.id and q.doctor_id=my_doctor_id()));
create policy admin_all_profiles on profiles for all to authenticated using(my_role()='admin') with check(my_role()='admin');

revoke all on all tables in schema public from anon,authenticated;grant select on profiles,doctors,offices,doctor_sessions,patients,service_points,medical_queue to authenticated;grant select on active_doctors_public,doctor_queue_view,reception_queue_view to authenticated;
grant execute on function public.get_display_state(text) to anon,authenticated;
grant execute on function public.search_patients(text),public.save_patient(jsonb),public.call_next_ticket(bigint),public.call_specific_ticket(bigint,int),public.recall_ticket(bigint),public.set_next_ticket(bigint,int),public.enqueue_patient(bigint,bigint),public.transfer_patient(bigint,bigint,text),public.start_doctor_session(bigint),public.end_doctor_session(),public.doctor_queue_action(bigint,text) to authenticated;
alter publication supabase_realtime add table public.ticket_calls,public.patient_calls,public.medical_queue,public.doctor_sessions;
commit;
