-- ============================================================
-- SCRIPT COMPLETO DDL E SEEDS - SISTEMA MÉDICO CMIP & MULTI-TV
-- Centro Médico Integrado Piratininga
-- Copie e cole no "SQL Editor" do seu Supabase Dashboard e clique em "RUN"
-- ============================================================

-- 1. TABELA DE CONSULTÓRIOS / SALAS (com TV de Destino)
CREATE TABLE IF NOT EXISTS public.offices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  code VARCHAR(20) NOT NULL,
  location VARCHAR(100),
  target_tv VARCHAR(20) NOT NULL DEFAULT '1', -- '1' = TV 01, '2' = TV 02, 'all' = Ambas as TVs
  active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Garantir colunas novas em bancos existentes
ALTER TABLE public.offices ADD COLUMN IF NOT EXISTS code VARCHAR(20);
ALTER TABLE public.offices ADD COLUMN IF NOT EXISTS location VARCHAR(100);
ALTER TABLE public.offices ADD COLUMN IF NOT EXISTS target_tv VARCHAR(20) DEFAULT '1';
ALTER TABLE public.offices ADD COLUMN IF NOT EXISTS active BOOLEAN DEFAULT TRUE;
ALTER TABLE public.offices ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

-- 2. TABELA DE MÉDICOS (Corpo Clínico)
CREATE TABLE IF NOT EXISTS public.doctors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  crm VARCHAR(30) NOT NULL,
  crm_uf VARCHAR(2) DEFAULT 'SP',
  specialty VARCHAR(100) NOT NULL DEFAULT 'Clínica Geral',
  phone VARCHAR(30),
  email VARCHAR(120),
  office_id BIGINT REFERENCES public.offices(id) ON DELETE SET NULL,
  office_name VARCHAR(100),
  active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Garantir colunas novas em bancos existentes
ALTER TABLE public.doctors ADD COLUMN IF NOT EXISTS crm_uf VARCHAR(2) DEFAULT 'SP';
ALTER TABLE public.doctors ADD COLUMN IF NOT EXISTS phone VARCHAR(30);
ALTER TABLE public.doctors ADD COLUMN IF NOT EXISTS email VARCHAR(120);
ALTER TABLE public.doctors ADD COLUMN IF NOT EXISTS active BOOLEAN DEFAULT TRUE;
ALTER TABLE public.doctors ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

-- 3. TABELA DE USUÁRIOS E AUTENTICAÇÃO
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  username VARCHAR(50) UNIQUE NOT NULL,
  password VARCHAR(100) NOT NULL,
  role VARCHAR(30) NOT NULL, -- 'admin', 'receptionist', 'doctor'
  doctor_id BIGINT REFERENCES public.doctors(id) ON DELETE SET NULL,
  active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Garantir colunas novas em bancos existentes
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS doctor_id BIGINT REFERENCES public.doctors(id) ON DELETE SET NULL;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS active BOOLEAN DEFAULT TRUE;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

-- 4. TABELA DE PACIENTES
CREATE TABLE IF NOT EXISTS public.patients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  document VARCHAR(30),
  phone VARCHAR(30),
  birth_date DATE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. TABELA DE FILA E CHAMADAS NOMINAIS (com Roteamento Multi-TV)
CREATE TABLE IF NOT EXISTS public.patient_calls (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  call_id INT NOT NULL DEFAULT 1,
  patient_id BIGINT REFERENCES public.patients(id) ON DELETE SET NULL,
  patient_name VARCHAR(150) NOT NULL,
  doctor_id BIGINT REFERENCES public.doctors(id) ON DELETE SET NULL,
  doctor_name VARCHAR(150) NOT NULL,
  office_name VARCHAR(100) NOT NULL,
  target_tv VARCHAR(20) NOT NULL DEFAULT '1', -- '1' = TV 01, '2' = TV 02, 'all' = Ambas
  type VARCHAR(30) DEFAULT 'Normal', -- 'Normal', 'Preferencial', 'Retorno'
  status VARCHAR(30) DEFAULT 'waiting', -- 'waiting', 'called', 'in_progress', 'completed', 'absent', 'cancelled'
  created_by_user VARCHAR(100),
  called_at TIMESTAMPTZ,
  finished_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Garantir colunas novas em bancos existentes
ALTER TABLE public.patient_calls ADD COLUMN IF NOT EXISTS target_tv VARCHAR(20) DEFAULT '1';
ALTER TABLE public.patient_calls ADD COLUMN IF NOT EXISTS finished_at TIMESTAMPTZ;

-- 6. TABELA LEGADA DE SENHAS NUMÉRICAS (Totem)
CREATE TABLE IF NOT EXISTS public.tickets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  call_id INT NOT NULL DEFAULT 1,
  number VARCHAR(20) NOT NULL,
  raw_number INT NOT NULL,
  desk VARCHAR(50) NOT NULL,
  target_tv VARCHAR(20) DEFAULT '1',
  type VARCHAR(20) DEFAULT 'Normal',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.tickets ADD COLUMN IF NOT EXISTS target_tv VARCHAR(20) DEFAULT '1';

-- 7. ÍNDICES DE ALTO DESEMPENHO
CREATE INDEX IF NOT EXISTS idx_patient_calls_target_tv ON public.patient_calls (target_tv, status);
CREATE INDEX IF NOT EXISTS idx_patient_calls_doctor_status ON public.patient_calls (doctor_id, status);
CREATE INDEX IF NOT EXISTS idx_patient_calls_id_desc ON public.patient_calls (id DESC);
CREATE INDEX IF NOT EXISTS idx_patient_calls_called_desc ON public.patient_calls (called_at DESC NULLS LAST);
CREATE INDEX IF NOT EXISTS idx_doctors_active ON public.doctors (active);
CREATE INDEX IF NOT EXISTS idx_offices_active ON public.offices (active);
CREATE INDEX IF NOT EXISTS idx_users_username ON public.users (username);

-- 8. HABILITAR ROW LEVEL SECURITY (RLS)
ALTER TABLE public.offices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.doctors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.patients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.patient_calls ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tickets ENABLE ROW LEVEL SECURITY;

-- Políticas de Leitura
DROP POLICY IF EXISTS "Leitura Geral Offices" ON public.offices;
CREATE POLICY "Leitura Geral Offices" ON public.offices FOR SELECT USING (true);

DROP POLICY IF EXISTS "Leitura Geral Doctors" ON public.doctors;
CREATE POLICY "Leitura Geral Doctors" ON public.doctors FOR SELECT USING (true);

DROP POLICY IF EXISTS "Leitura Geral Users" ON public.users;
CREATE POLICY "Leitura Geral Users" ON public.users FOR SELECT USING (true);

DROP POLICY IF EXISTS "Leitura Geral Patients" ON public.patients;
CREATE POLICY "Leitura Geral Patients" ON public.patients FOR SELECT USING (true);

DROP POLICY IF EXISTS "Leitura Geral PatientCalls" ON public.patient_calls;
CREATE POLICY "Leitura Geral PatientCalls" ON public.patient_calls FOR SELECT USING (true);

DROP POLICY IF EXISTS "Leitura Geral Tickets" ON public.tickets;
CREATE POLICY "Leitura Geral Tickets" ON public.tickets FOR SELECT USING (true);

-- Políticas de Escrita
DROP POLICY IF EXISTS "Escrita Geral Offices" ON public.offices;
CREATE POLICY "Escrita Geral Offices" ON public.offices FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Escrita Geral Doctors" ON public.doctors;
CREATE POLICY "Escrita Geral Doctors" ON public.doctors FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Escrita Geral Users" ON public.users;
CREATE POLICY "Escrita Geral Users" ON public.users FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Escrita Geral Patients" ON public.patients;
CREATE POLICY "Escrita Geral Patients" ON public.patients FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Escrita Geral PatientCalls" ON public.patient_calls;
CREATE POLICY "Escrita Geral PatientCalls" ON public.patient_calls FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Escrita Geral Tickets" ON public.tickets;
CREATE POLICY "Escrita Geral Tickets" ON public.tickets FOR ALL USING (true) WITH CHECK (true);

-- 9. CARGA DE DADOS INICIAIS (SEEDS MULTI-TV)
-- Consultórios com TV 01 e TV 02
INSERT INTO public.offices (name, code, location, target_tv)
VALUES 
  ('Consultório 01 - Clínica Geral', 'C01', 'Térreo - Ala A', '1'),
  ('Consultório 02 - Cardiologia', 'C02', '1º Andar - Ala B', '2'),
  ('Consultório 03 - Ortopedia', 'C03', 'Térreo - Ala A', '1'),
  ('Consultório 04 - Pediatria', 'C04', '1º Andar - Ala B', '2')
ON CONFLICT DO NOTHING;

-- Médicos Iniciais
INSERT INTO public.doctors (name, crm, crm_uf, specialty, office_name)
VALUES 
  ('Dr. Carlos Eduardo', '12345', 'SP', 'Clínica Geral', 'Consultório 01 - Clínica Geral'),
  ('Dra. Helena Martins', '67890', 'SP', 'Cardiologia', 'Consultório 02 - Cardiologia'),
  ('Dr. Roberto Silva', '54321', 'SP', 'Ortopedia', 'Consultório 03 - Ortopedia')
ON CONFLICT DO NOTHING;

-- Usuários Iniciais
INSERT INTO public.users (name, username, password, role, doctor_id)
VALUES 
  ('Administrador Geral', 'admin', 'admin123', 'admin', NULL),
  ('Recepção Principal', 'recepcao', 'recepcao123', 'receptionist', NULL),
  ('Dr. Carlos Eduardo', 'dr_carlos', 'medico123', 'doctor', 1),
  ('Dra. Helena Martins', 'dra_helena', 'medico123', 'doctor', 2)
ON CONFLICT (username) DO NOTHING;
