-- ============================================================
-- SCRIPT COMPLETO DDL E SEEDS - SISTEMA MÉDICO CMIP & SENHAS
-- Copie e cole no "SQL Editor" do seu Supabase Dashboard e clique em "RUN"
-- ============================================================

-- 1. Tabela de Consultórios / Salas
CREATE TABLE IF NOT EXISTS public.offices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  code VARCHAR(20),
  active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tabela de Médicos
CREATE TABLE IF NOT EXISTS public.doctors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  crm VARCHAR(30),
  specialty VARCHAR(100),
  office_id BIGINT REFERENCES public.offices(id) ON DELETE SET NULL,
  office_name VARCHAR(100),
  active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Tabela de Usuários e Autenticação (ADMs, Recepção, Médicos)
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  username VARCHAR(50) UNIQUE NOT NULL,
  password VARCHAR(100) NOT NULL,
  role VARCHAR(30) NOT NULL, -- 'admin', 'receptionist', 'doctor'
  doctor_id BIGINT REFERENCES public.doctors(id) ON DELETE SET NULL,
  active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Tabela de Pacientes
CREATE TABLE IF NOT EXISTS public.patients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  document VARCHAR(30),
  phone VARCHAR(30),
  birth_date DATE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Tabela de Fila e Chamadas Nominais (Fluxo Direto Recepção -> Médico)
CREATE TABLE IF NOT EXISTS public.patient_calls (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  call_id INT NOT NULL DEFAULT 1,
  patient_id BIGINT REFERENCES public.patients(id) ON DELETE CASCADE,
  patient_name VARCHAR(150) NOT NULL,
  doctor_id BIGINT REFERENCES public.doctors(id) ON DELETE SET NULL,
  doctor_name VARCHAR(120) NOT NULL,
  office_name VARCHAR(100) NOT NULL,
  type VARCHAR(30) DEFAULT 'Normal', -- 'Normal', 'Preferencial', 'Retorno'
  status VARCHAR(30) DEFAULT 'waiting', -- 'waiting', 'called', 'in_progress', 'completed', 'absent'
  created_by_user VARCHAR(100),
  called_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Tabela Legada de Senhas Numéricas (tickets)
CREATE TABLE IF NOT EXISTS public.tickets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  call_id INT NOT NULL DEFAULT 1,
  number VARCHAR(20) NOT NULL,
  raw_number INT NOT NULL,
  desk VARCHAR(50) NOT NULL,
  type VARCHAR(20) DEFAULT 'Normal',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Índices de Desempenho
CREATE INDEX IF NOT EXISTS idx_patient_calls_id_desc ON public.patient_calls (id DESC);
CREATE INDEX IF NOT EXISTS idx_patient_calls_status ON public.patient_calls (status);
CREATE INDEX IF NOT EXISTS idx_patient_calls_doctor ON public.patient_calls (doctor_id, status);
CREATE INDEX IF NOT EXISTS idx_tickets_id_desc ON public.tickets (id DESC);

-- 8. Habilitar RLS e Criar Políticas
ALTER TABLE public.offices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.doctors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.patients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.patient_calls ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tickets ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Permitir Leitura Geral" ON public.offices FOR SELECT USING (true);
CREATE POLICY "Permitir Leitura Médicos" ON public.doctors FOR SELECT USING (true);
CREATE POLICY "Permitir Leitura Usuários" ON public.users FOR SELECT USING (true);
CREATE POLICY "Permitir Leitura Pacientes" ON public.patients FOR SELECT USING (true);
CREATE POLICY "Permitir Leitura Chamadas" ON public.patient_calls FOR SELECT USING (true);
CREATE POLICY "Permitir Leitura Senhas" ON public.tickets FOR SELECT USING (true);

CREATE POLICY "Permitir Escrita Geral Offices" ON public.offices FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Permitir Escrita Geral Doctors" ON public.doctors FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Permitir Escrita Geral Users" ON public.users FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Permitir Escrita Geral Patients" ON public.patients FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Permitir Escrita Geral PatientCalls" ON public.patient_calls FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Permitir Escrita Geral Tickets" ON public.tickets FOR ALL USING (true) WITH CHECK (true);

-- 9. Inserção de Dados Iniciais (SEEDS)
INSERT INTO public.offices (name, code)
VALUES 
  ('Consultório 01', 'C01'),
  ('Consultório 02', 'C02'),
  ('Consultório 03', 'C03'),
  ('Recepção Principal', 'REC')
ON CONFLICT DO NOTHING;

INSERT INTO public.doctors (name, crm, specialty, office_name)
VALUES 
  ('Dr. Carlos Eduardo', 'CRM 12345-SP', 'Clínica Geral', 'Consultório 01'),
  ('Dra. Helena Martins', 'CRM 67890-SP', 'Cardiologia', 'Consultório 02'),
  ('Dr. Roberto Silva', 'CRM 54321-SP', 'Ortopedia', 'Consultório 03')
ON CONFLICT DO NOTHING;

INSERT INTO public.users (name, username, password, role, doctor_id)
VALUES 
  ('Administrador Geral', 'admin', 'admin123', 'admin', NULL),
  ('Recepção CMIP', 'recepcao', 'recepcao123', 'receptionist', NULL),
  ('Dr. Carlos Eduardo', 'dr_carlos', 'medico123', 'doctor', 1),
  ('Dra. Helena Martins', 'dra_helena', 'medico123', 'doctor', 2)
ON CONFLICT (username) DO NOTHING;
