-- ============================================================
-- SCRIPT DE CRIAÇÃO E CONFIGURAÇÃO DA TABELA CMIP NO SUPABASE
-- Copie e cole este código no "SQL Editor" do seu Supabase Dashboard
-- ============================================================

-- 1. Criação da Tabela de Senhas com Suporte a call_id Sequencial
CREATE TABLE IF NOT EXISTS public.tickets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  call_id INT NOT NULL DEFAULT 1,
  number VARCHAR(20) NOT NULL,
  raw_number INT NOT NULL,
  desk VARCHAR(50) NOT NULL,
  type VARCHAR(20) DEFAULT 'Normal',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Índices de Alta Performance para o Painel da TV
CREATE INDEX IF NOT EXISTS idx_tickets_id_desc ON public.tickets (id DESC);
CREATE INDEX IF NOT EXISTS idx_tickets_call_id ON public.tickets (call_id DESC);

-- 3. Habilitar RLS (Row Level Security) e Liberar Acesso para a Aplicação
ALTER TABLE public.tickets ENABLE ROW LEVEL SECURITY;

-- Remover políticas antigas se existirem para evitar conflito
DROP POLICY IF EXISTS "Permitir Leitura Pública de Senhas" ON public.tickets;
DROP POLICY IF EXISTS "Permitir Inserção Pública de Senhas" ON public.tickets;
DROP POLICY IF EXISTS "Permitir Zerar Fila" ON public.tickets;

-- Criar Políticas de Acesso Público
CREATE POLICY "Permitir Leitura Pública de Senhas" 
ON public.tickets FOR SELECT 
USING (true);

CREATE POLICY "Permitir Inserção Pública de Senhas" 
ON public.tickets FOR INSERT 
WITH CHECK (true);

CREATE POLICY "Permitir Zerar Fila" 
ON public.tickets FOR DELETE 
USING (true);

-- 4. Função Stored Procedure para Zerar a Fila de Forma Rápida (Opcional)
CREATE OR REPLACE FUNCTION public.reset_cmip_queue()
RETURNS void AS $$
BEGIN
  TRUNCATE TABLE public.tickets RESTART IDENTITY;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
