import React, { useEffect, useRef, useState } from 'react';
import { Clock, Film, Maximize2, Monitor, Star, Stethoscope, Volume2, VolumeX, Wifi } from 'lucide-react';
import { cmipApi } from '../utils/cmipApi';
import { announceTicket, isAudioContextRunning, warmupAudio } from '../utils/audio';

const VIDEOS=['/WhatsApp Video 2026-08-30 at 15.44.26.mp4','/WhatsApp Video 2026-08-30 at 15.44.26 (1).mp4'];
const sleep=(ms)=>new Promise(r=>setTimeout(r,ms));
const normalize=(e)=>e?({
  id:e.event_key,event_key:e.event_key,kind:e.kind,isRepeat:Boolean(e.is_recall),
  number:e.display_number||'',patientName:e.patient_name||'',desk:e.destination||'',officeName:e.destination||'',
  timestamp:e.at?new Date(e.at).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'}):''
}):null;

export default function V1TvPanel({slug}){
  const[current,setCurrent]=useState(null),[history,setHistory]=useState([]),[panel,setPanel]=useState(null),[connected,setConnected]=useState(true),[calling,setCalling]=useState(false),[activated,setActivated]=useState(false),[video,setVideo]=useState(0),[muted,setMuted]=useState(true),[time,setTime]=useState(''),[date,setDate]=useState(''),[missing,setMissing]=useState(false);
  const videoRef=useRef(null),first=useRef(true),seen=useRef(new Set()),queue=useRef([]),processing=useRef(false);

  const processQueue=async()=>{if(processing.current)return;processing.current=true;try{while(queue.current.length){const item=queue.current.shift();if(!item)continue;setCurrent(item);setHistory(h=>[item,...h.filter(x=>x.event_key!==item.event_key)].slice(0,8));setCalling(true);try{if(videoRef.current)videoRef.current.pause();await Promise.race([announceTicket(item),sleep(10000)])}catch(e){console.error('[TV audio]',e)}finally{if(videoRef.current){const p=videoRef.current.play();if(p&&p.catch)p.catch(()=>{})}}await sleep(3000);setCalling(false);await sleep(400)}}finally{processing.current=false;if(queue.current.length)setTimeout(processQueue,50)}};
  const enqueue=(item)=>{if(!item||seen.current.has(item.event_key))return;seen.current.add(item.event_key);if(seen.current.size>200)seen.current=new Set(Array.from(seen.current).slice(-100));queue.current.push(item);processQueue()};
  const load=async({announce=true}={})=>{try{const s=await cmipApi.panelState(slug);if(!s){setMissing(true);return}setMissing(false);setConnected(true);setPanel(s.panel||null);const next=normalize(s.current);const hist=(s.history||[]).map(normalize).filter(Boolean);if(first.current){first.current=false;if(next)seen.current.add(next.event_key);setCurrent(next);setHistory(hist);return}if(next&&announce)enqueue(next);if(!processing.current)setHistory(hist)}catch(e){console.error('[TV state]',e);setConnected(false)}};
  useEffect(()=>{const tick=()=>{const n=new Date();setTime(n.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'}));setDate(n.toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long',year:'numeric'}))};tick();const t=setInterval(tick,1000);warmupAudio();if(isAudioContextRunning())setActivated(true);load({announce:false});const off=cmipApi.subscribeDisplay(slug,()=>load({announce:true}),s=>setConnected(s));const poll=setInterval(()=>load({announce:true}),10000);return()=>{clearInterval(t);clearInterval(poll);if(off)off()}},[slug]);
  useEffect(()=>{if(videoRef.current)videoRef.current.load();if(videoRef.current){const p=videoRef.current.play();if(p&&p.catch)p.catch(()=>{})}},[video]);
  const activate=async()=>{warmupAudio();setActivated(true);setMuted(true);if(videoRef.current){try{const playPromise=videoRef.current.play();if(playPromise&&playPromise.then)await playPromise}catch(e){console.warn('[TV video unlock]',e)}}try{if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen()}catch(e){console.warn('[TV fullscreen]',e)}};
  const fullscreen=async()=>{try{if(!document.fullscreenElement)document.documentElement.requestFullscreen?await document.documentElement.requestFullscreen():null;else document.exitFullscreen?await document.exitFullscreen():null}catch{}};
  if(missing)return <main className="h-screen bg-cmip-950 text-white grid place-items-center p-8"><div className="text-center"><Monitor className="w-14 h-14 mx-auto text-cmip-400"/><h1 className="text-3xl font-black mt-4">TV não encontrada ou inativa</h1><p className="text-cmip-100/60 mt-2">Verifique o identificador deste display.</p></div></main>;
  const isMedical=current?.kind==='medical';const displayName=current?(isMedical?current.patientName:current.number):'----';const location=current?.officeName||current?.desk||'Aguardando chamada';
  return <div className="h-screen w-screen bg-cmip-950 text-slate-100 font-['Montserrat',sans-serif] flex flex-col overflow-hidden cmip-plus-pattern relative">
    {!activated&&<button onClick={activate} className="absolute inset-0 z-50 bg-cmip-950/95 text-white grid place-items-center text-center p-8"><div><Volume2 className="w-16 h-16 mx-auto text-cmip-400"/><div className="text-4xl font-black mt-5">ATIVAR PAINEL</div><p className="mt-3 text-cmip-100/70">Ativa áudio, vídeo e tela cheia para uso na televisão.</p></div></button>}
    <header className="h-16 md:h-20 px-4 md:px-6 flex items-center justify-between border-b border-cmip-600/30 bg-cmip-900/90 shrink-0 z-10">
      <div className="flex items-center gap-3"><div className="bg-white p-1.5 rounded-xl"><img src="/logo.png" className="h-9 md:h-11 object-contain"/></div><div><h1 className="font-black text-sm md:text-lg uppercase"><span className="text-cmip-400">CMIP</span> Painel de Atendimento</h1><p className="text-[9px] md:text-xs text-cmip-100/60 uppercase">{panel?.name||slug}</p></div></div>
      <div className="flex items-center gap-2"><button onClick={fullscreen} className="p-2 rounded-lg border border-cmip-600/30 bg-cmip-950" title="Tela cheia"><Maximize2 className="w-4 h-4"/></button><div className={`px-2 py-1 rounded-lg border flex items-center gap-1 text-[9px] font-bold ${connected?'text-emerald-400 border-emerald-500/30':'text-rose-400 border-rose-500/30'}`}><Wifi className="w-3 h-3"/>{connected?'ONLINE':'OFFLINE'}</div></div>
    </header>
    <main className="flex-1 grid grid-cols-2 gap-3 md:gap-4 p-3 md:p-4 min-h-0 overflow-hidden z-10">
      <div className="flex flex-col gap-3 min-h-0">
        <div className={`flex-1 rounded-3xl p-4 md:p-5 flex flex-col justify-between items-center text-center glass-panel min-h-0 bg-cmip-900/70 border shadow-2xl transition-all ${calling?'animate-tv-glow border-cmip-400 bg-cmip-900/95 scale-[1.008]':'border-cmip-600/30'}`}>
          <div className="w-full flex items-center justify-between"><span className="px-4 py-1.5 rounded-full text-xs md:text-sm font-black uppercase tracking-wider bg-emerald-400 text-cmip-950">{isMedical?<><Stethoscope className="inline w-4 h-4 mr-1"/>CONSULTA MÉDICA</>:'SENHA DA RECEPÇÃO'}</span><span className="px-3 py-1 rounded-full border border-cmip-500/40 bg-cmip-950/80 text-xs font-bold"><Clock className="inline w-3 h-3 mr-1 text-cmip-400"/>{time||'--:--'}</span></div>
          <div className="my-auto py-2 flex flex-col items-center justify-center max-w-4xl"><p className="text-xs md:text-sm text-cmip-400 font-bold uppercase tracking-[0.25em] mb-1">{isMedical?'PACIENTE':'SENHA ATUAL'}</p><div className={`${isMedical?'text-4xl sm:text-5xl md:text-6xl lg:text-7xl':'text-6xl sm:text-7xl md:text-8xl lg:text-9xl'} font-black tracking-tight text-white leading-tight uppercase`}>{displayName}</div></div>
          <div className="w-full pt-3 border-t border-cmip-600/30"><p className="text-[10px] md:text-xs text-cmip-400 font-bold uppercase tracking-[0.2em]">LOCAL DE ATENDIMENTO</p><div className="text-2xl md:text-4xl xl:text-5xl font-black text-amber-300 uppercase">{location}</div></div>
        </div>
        <div className="h-36 md:h-40 rounded-3xl p-3 bg-cmip-900/65 border border-cmip-600/30 glass-panel overflow-hidden shadow-2xl shrink-0"><div className="flex items-center justify-between mb-2 pb-1 border-b border-cmip-600/30"><h2 className="text-xs md:text-sm font-bold uppercase flex items-center gap-2"><Clock className="w-4 h-4 text-cmip-400"/>Últimas Chamadas</h2><span className="text-[10px] bg-emerald-950 text-emerald-300 border border-emerald-500/40 px-2 py-0.5 rounded-full">{panel?.name||'CMIP'}</span></div><div className="grid grid-cols-3 gap-2 h-[76px]">{history.slice(1,4).map(x=><div key={x.event_key} className="p-2 rounded-xl bg-cmip-950/80 border border-cmip-600/40 overflow-hidden"><div className="text-xs md:text-sm font-black truncate">{x.kind==='medical'?x.patientName:x.number}</div><div className="text-[10px] font-bold text-amber-300 truncate">{x.officeName||x.desk}</div><div className="text-[9px] mt-2 text-cmip-400">{x.timestamp}</div></div>)}{history.length<=1&&<div className="col-span-3 grid place-items-center text-xs text-cmip-100/50">Nenhuma chamada anterior neste painel</div>}</div></div>
      </div>
      <div className="h-full rounded-3xl p-4 bg-cmip-900/70 border border-cmip-600/40 glass-panel shadow-2xl overflow-hidden flex flex-col min-h-0"><div className="flex items-center justify-between mb-2"><span className="text-xs md:text-sm font-black uppercase flex items-center gap-2"><Film className="w-4 h-4 text-cmip-400"/>CMIP VÍDEOS INSTITUCIONAIS</span><div className="flex gap-2 items-center"><span className="text-xs font-mono bg-cmip-950 px-2 py-1 rounded">{video+1} / {VIDEOS.length}</span><button onClick={()=>setMuted(!muted)} className="p-1.5 rounded-xl bg-cmip-950 border border-cmip-600/30">{muted?<VolumeX className="w-4 h-4 text-amber-400"/>:<Volume2 className="w-4 h-4 text-emerald-400"/>}</button></div></div><div className="relative flex-1 rounded-2xl overflow-hidden bg-black border border-cmip-600/20"><video ref={videoRef} key={video} src={VIDEOS[video]} autoPlay muted={muted} playsInline preload="auto" onEnded={()=>setVideo((video+1)%VIDEOS.length)} className="w-full h-full object-contain bg-black"/></div><p className="text-[10px] text-cmip-100/50 mt-2 text-center capitalize">{date}</p></div>
    </main>
  </div>
}
